on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.0'
          cache: false

      - name: Build amd64
        run: |
          GOOS=darwin GOARCH=amd64 go build -buildvcs=false -ldflags="-X main.version=$(git describe --always --tags)" -o appfuk-x86_64

      - name: Build arm64
        run: |
          GOOS=darwin GOARCH=arm64 go build -buildvcs=false -ldflags="-X main.version=$(git describe --always --tags)" -o appfuk-arm64

      - name: Lipo
        run: |
          go install github.com/konoui/lipo@latest
          lipo -create appfuk-x86_64 appfuk-arm64 -output appfuk

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: appfuk
          path: |
            appfuk
